apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: myl7u3g8k-java-quarkus 
  janus-idp.io/tekton: myl7u3g8k-java-quarkus
  backstage.io/kubernetes-id: myl7u3g8k-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: myl7u3g8k-java-quarkus
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml